apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor
  namespace: argocd
  labels:
    curso: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ThiagoLange/argocd-estudos.git
    path: applications
    targetRevision: HEAD
    directory:
      recurse: true
      # exclude: 'nginx/*'
      # include: 'nginx/*'
  destination:
    server: https://kubernetes.default.svc
    namespace: webcolor
  info:
    - name: Projeto
      value: "Curso Gitops"
  #syncPolicy:
   # syncOptions:
    #  - CreateNamespace=true
    #automated:
     # selfHeal: true
     # prune: true 