apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/veronez-dev/web-page-deploy.git
    path: k8s/caos
    targetRevision: HEAD
  destination:
    namespace: caos
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: web
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      name: web
      jsonPointers:
        - /status/currentReplicas
        - /status/desiredReplicas