apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  labels:
    curso: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/ThiagoLange/argocd-estudos.git
    path: applications/nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  info:
    - name: Projeto
      value: "Curso Gitops"