apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-color
  namespace: argocd
spec:
  # Vamos definir aqui a fonte do manifesto
  source:
    # Repositório Git
    repoURL: https://github.com/fabricioveronez/web-color-deploy.git
    # Diretório
    path: k8s
    # Target revision
    targetRevision: HEAD
  revisionHistoryLimit: 4
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=Foreground # Background or orphan
      - PruneLast=false # true
      - RespectIgnoreDifferences=true # or false
      - ApplyOutOfSyncOnly=false # or true  
  # Agora vamos definir o ambiente que vai ser usado
  destination:
    namespace: web-color
    server: https://kubernetes.default.svc
  # Definindo o projeto (aqui vai ser o default)
  project: default