apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ThiagoLange/argocd-estudos.git
    targetRevision: HEAD
    path: workloads/nginx # <--- Aponta para a pasta do workload
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx